//------------------------------------------------------------------
//                   !!! WARNING !!! 
//
// This file is auto generated by ctrpp.exe utility from performance
// counters manifest:
//
// C:/Users/andre/Documents/GitHub/openzfs/module/os/windows/OpenZFS.man
//
// It should be regenerated every time the code is built.
// Do not check it in.
//-------------------------------------------------------------------

#pragma once

#define ZFSinPerfGuid { 0x11b6ca09, 0xa1c6, 0x44b9, 0xaa, 0xb6, 0x73, 0xbe, 0x31, 0x5f, 0xd7, 0x99 }
#define ZFSinPerfVdevGuid { 0x3e687ea1, 0x7258, 0x43bf, 0xb8, 0x32, 0xf0, 0x82, 0xec, 0x2, 0xf1, 0xca }
#define ZFSinCachePerfGuid { 0x2f8f7f86, 0x5c0b, 0x4865, 0x97, 0x2c, 0xa7, 0x88, 0xf0, 0x4c, 0x61, 0xaa }

#define ZFSinPerfGuidString L"{11b6ca09-a1c6-44b9-aab6-73be315fd799}"
#define ZFSinPerfVdevGuidString L"{3e687ea1-7258-43bf-b832-f082ec02f1ca}"
#define ZFSinCachePerfGuidString L"{2f8f7f86-5c0b-4865-972c-a788f04c61aa}"

#define ZFSinPerfName L"OpenZFS Zpool"
#define ZFSinPerfVdevName L"OpenZFS Vdev"
#define ZFSinCachePerfName L"OpenZFS Cache"









