name: rebase_info

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        #repository: openzfsonwindows/openzfs
        fetch-depth: 0
    
    - run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - run: git remote add openzfs https://github.com/openzfs/zfs.git
      
    - run: git fetch --all
      
    - run: git rebase openzfs/master
